apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: netflix-app-hpa
  namespace: netflix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: netflix-app
  minReplicas: 2         # same as your deployment default
  maxReplicas: 10        # scale up to 10 pods
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60   # scale out if avg CPU > 60%
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70   # optional: scale if memory > 70%
